"use client";

import * as React from "react";
import { Container } from "@/components/container";
import { Button } from "@/components/ui/button";
import { API_URL } from "@/lib/api-url";

const labels: Record<string,string> = { REQUESTED:"تم استلام الطلب", RESERVATION_PENDING:"جاري الحجز المبدئي", PROVISIONAL_TICKET:"تم إصدار الحجز المبدئي", PAYMENT_PENDING:"بانتظار الدفع", PAYMENT_UNDER_REVIEW:"إشعار الدفع قيد المراجعة", PAYMENT_CONFIRMED:"تم تأكيد الدفع", FINAL_TICKET_ISSUED:"تم إصدار الحجز النهائي", CANCELLED:"ملغي" };

export default function FlightBookingPage() {
  const [number,setNumber]=React.useState(""); const [phone,setPhone]=React.useState(""); const [booking,setBooking]=React.useState<any>(null); const [file,setFile]=React.useState<File|null>(null); const [loading,setLoading]=React.useState(false); const [error,setError]=React.useState("");
  async function search(e:React.FormEvent){e.preventDefault();setLoading(true);setError("");try{const r=await fetch(`${API_URL}/flight-bookings/public/${encodeURIComponent(number.trim())}?phone=${encodeURIComponent(phone.trim())}`);const d=await r.json();if(!r.ok)throw Error(d.message||"تعذر العثور على الحجز");setBooking(d.booking)}catch(e){setBooking(null);setError(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false)}}
  async function uploadReceipt(e:React.FormEvent){e.preventDefault();if(!file)return;setLoading(true);setError("");try{const fd=new FormData();fd.append("file",file);fd.append("phone",phone);const r=await fetch(`${API_URL}/flight-bookings/${encodeURIComponent(booking.id)}/payment-receipt`,{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw Error(d.message||"تعذر رفع الإشعار");setBooking(d.booking);setFile(null)}catch(e){setError(e instanceof Error?e.message:"حدث خطأ")}finally{setLoading(false)}}
  return <main className="py-16"><Container><div className="mx-auto max-w-3xl"><div className="mb-8 text-center"><p className="text-sm font-bold text-primary">✈️ متابعة حجز الطيران</p><h1 className="mt-2 text-3xl font-black">تابع حجزك وادفع بأمان</h1><p className="mt-2 text-muted-foreground">أدخل رقم الحجز ورقم الهاتف المسجل في الطلب.</p></div>
  {!booking?<form onSubmit={search} className="rounded-3xl border bg-card p-6 shadow-sm"><div className="grid gap-4 sm:grid-cols-2"><input required value={number} onChange={e=>setNumber(e.target.value)} placeholder="رقم الحجز FLT-..." className="h-12 rounded-xl border bg-background px-4"/><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="رقم الهاتف / واتساب" className="h-12 rounded-xl border bg-background px-4"/></div>{error&&<p className="mt-4 text-sm font-bold text-destructive">{error}</p>}<Button className="mt-5 w-full" size="lg" variant="gold" disabled={loading}>{loading?"جاري التحقق...":"متابعة الحجز"}</Button></form>:
  <div className="space-y-5"><section className="rounded-3xl border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">رقم الحجز</p><h2 className="text-2xl font-black">{booking.booking_number}</h2><p className="mt-2 font-bold">{booking.customer_name}</p></div><span className="rounded-full bg-primary/10 px-4 py-2 text-sm font-bold text-primary">{labels[booking.status]||booking.status}</span></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">المبلغ</p><p className="font-black">{Number(booking.amount).toLocaleString()} {booking.currency}</p></div><div><p className="text-xs text-muted-foreground">المسافرون</p><p className="font-black">{Array.isArray(booking.passengers)?booking.passengers.length:0}</p></div><div><p className="text-xs text-muted-foreground">الهاتف</p><p className="font-black" dir="ltr">{booking.customer_phone}</p></div></div></section>
  {booking.provisional_ticket_path&&<section className="rounded-3xl border bg-card p-6"><h3 className="text-xl font-black">الحجز المبدئي</h3><p className="mt-2 text-sm text-muted-foreground">تم حجز الرحلة مبدئيًا. راجع الملف ثم أكمل الدفع.</p><a className="mt-4 inline-flex rounded-xl border px-4 py-3 font-bold" href={`${API_URL}/flight-bookings/${booking.id}/file/provisional`} target="_blank">عرض / تحميل الحجز المبدئي</a></section>}
  {["PAYMENT_PENDING","PAYMENT_UNDER_REVIEW"].includes(booking.status)&&<section className="rounded-3xl border bg-card p-6"><h3 className="text-xl font-black">💳 الدفع</h3><p className="mt-2 text-sm text-muted-foreground">حوّل المبلغ إلى أحد الحسابات التالية ثم ارفع إشعار الدفع.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{(booking.bankAccounts||[]).map((a:any)=><div key={a.id} className="rounded-2xl border p-4"><p className="font-black">{a.label}</p>{a.bank_name&&<p className="text-sm text-muted-foreground">{a.bank_name}</p>}<p className="mt-2 font-black" dir="ltr">{a.account_number}</p></div>)}</div>{booking.status==="PAYMENT_PENDING"?<form onSubmit={uploadReceipt} className="mt-5"><input required type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="block w-full rounded-xl border p-3"/><Button className="mt-3 w-full" variant="gold" disabled={loading}>{loading?"جاري الرفع...":"رفع إشعار الدفع"}</Button></form>:<p className="mt-4 rounded-xl bg-amber-500/10 p-3 text-sm font-bold">تم استلام إشعار الدفع، وهو الآن قيد المراجعة من فريق نسائم.</p>}</section>}
  {booking.status==="PAYMENT_CONFIRMED"&&<section className="rounded-3xl border bg-card p-6"><h3 className="text-xl font-black">✅ تم تأكيد الدفع</h3><p className="mt-2 text-sm text-muted-foreground">سيقوم الموظف بإصدار الحجز النهائي.</p></section>}
  {booking.final_ticket_path&&<section className="rounded-3xl border bg-card p-6"><h3 className="text-xl font-black">🎫 الحجز النهائي</h3><p className="mt-2 text-sm text-muted-foreground">تم إصدار تذكرتك النهائية.</p><a className="mt-4 inline-flex rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground" href={`${API_URL}/flight-bookings/${booking.id}/file/final`} target="_blank">عرض / تحميل التذكرة النهائية</a></section>}
  {error&&<p className="text-sm font-bold text-destructive">{error}</p>}<button className="text-sm font-bold text-muted-foreground underline" onClick={()=>setBooking(null)}>متابعة حجز آخر</button></div>}</div></Container></main>;
}
