import { useMemo,useState } from "react";
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { colors } from "../src/theme";
type DocState={passport:boolean;guarantorId:boolean}; type Traveler={id:string;name:string;passport:string;nationality:string;guarantorNumber:string;docs:DocState};
const makeTraveler=(n:number):Traveler=>({id:`traveler-${Date.now()}-${n}`,name:"",passport:"",nationality:"",guarantorNumber:"",docs:{passport:false,guarantorId:false}});
export default function UmrahScreen(){
 const [travelers,setTravelers]=useState<Traveler[]>([makeTraveler(1)]); const [review,setReview]=useState(false);
 const update=(id:string,patch:Partial<Traveler>)=>setTravelers(v=>v.map(t=>t.id===id?{...t,...patch}:t));
 const toggleDoc=(id:string,key:keyof DocState)=>setTravelers(v=>v.map(t=>t.id===id?{...t,docs:{...t.docs,[key]:!t.docs[key]}}:t));
 const complete=useMemo(()=>travelers.every(t=>t.name.trim()&&t.passport.trim()&&t.nationality.trim()&&t.guarantorNumber.trim()&&t.docs.passport&&t.docs.guarantorId),[travelers]);
 if(review)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.title}>مراجعة طلب العمرة</Text>{travelers.map((t,i)=><View key={t.id} style={s.card}><Text style={s.cardTitle}>مسافر {i+1} — {t.name}</Text><Text style={s.line}>الجواز: {t.passport}</Text><Text style={s.line}>الجنسية: {t.nationality}</Text><Text style={s.ok}>✓ مستندات هذا المسافر مكتملة</Text></View>)}<Text style={s.note}>السعر وتعليمات الدفع النهائية تظهر بعد مراجعة الوكالة واعتماد الطلب.</Text><View style={s.actions}><Pressable style={s.outline} onPress={()=>setReview(false)}><Text style={s.outlineText}>تعديل</Text></Pressable><Pressable style={s.primary}><Text style={s.primaryText}>إرسال الطلب</Text></Pressable></View></ScrollView></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.title}>طلب عمرة</Text><Text style={s.desc}>أدخل بيانات كل مسافر وارفع مستنداته بصورة مستقلة.</Text>{travelers.map((t,i)=><View key={t.id} style={s.card}><View style={s.cardHead}><Text style={s.cardTitle}>مسافر {i+1}</Text>{travelers.length>1&&<Pressable onPress={()=>setTravelers(v=>v.filter(x=>x.id!==t.id))}><Text style={s.remove}>حذف</Text></Pressable>}</View><TextInput value={t.name} onChangeText={name=>update(t.id,{name})} placeholder="الاسم الكامل" style={s.input} textAlign="right"/><View style={s.two}><TextInput value={t.passport} onChangeText={passport=>update(t.id,{passport})} placeholder="رقم الجواز" style={[s.input,s.flex]} textAlign="right"/><TextInput value={t.nationality} onChangeText={nationality=>update(t.id,{nationality})} placeholder="الجنسية" style={[s.input,s.flex]} textAlign="right"/></View><TextInput value={t.guarantorNumber} onChangeText={guarantorNumber=>update(t.id,{guarantorNumber})} placeholder="رقم الضامن" style={s.input} textAlign="right"/><DocRow label="صورة الجواز" done={t.docs.passport} onPress={()=>toggleDoc(t.id,"passport")}/><DocRow label="هوية الضامن / أبشر" done={t.docs.guarantorId} onPress={()=>toggleDoc(t.id,"guarantorId")}/></View>)}<Pressable style={s.add} onPress={()=>setTravelers(v=>[...v,makeTraveler(v.length+1)])}><Text style={s.addText}>+ إضافة مسافر</Text></Pressable><Pressable disabled={!complete} style={[s.primary,!complete&&s.disabled]} onPress={()=>setReview(true)}><Text style={s.primaryText}>مراجعة الطلب</Text></Pressable></ScrollView></SafeAreaView>;
}
function DocRow({label,done,onPress}:{label:string;done:boolean;onPress:()=>void}){return <View style={s.doc}><View><Text style={s.docLabel}>{label}</Text><Text style={done?s.ok:s.pending}>{done?"تم الإرفاق":"مطلوب"}</Text></View><Pressable onPress={onPress} style={[s.docButton,done&&s.docDone]}><Text style={done?s.docDoneText:s.docButtonText}>{done?"إزالة":"رفع"}</Text></Pressable></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},page:{padding:20,gap:14,paddingBottom:40},title:{fontSize:20,fontWeight:"800",color:colors.navy,textAlign:"right"},desc:{fontSize:12,color:colors.muted,textAlign:"right"},card:{backgroundColor:"#FFF",borderWidth:1,borderColor:colors.border,borderRadius:14,padding:14,gap:10},cardHead:{flexDirection:"row-reverse",justifyContent:"space-between"},cardTitle:{fontSize:13,fontWeight:"800",color:colors.navy,textAlign:"right"},remove:{color:colors.danger,fontSize:11,fontWeight:"700"},input:{backgroundColor:colors.soft,borderWidth:1,borderColor:colors.border,borderRadius:9,padding:11,fontSize:12.5},two:{flexDirection:"row-reverse",gap:8},flex:{flex:1},doc:{backgroundColor:colors.soft,borderRadius:9,padding:10,flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},docLabel:{fontSize:11.5,color:colors.text,textAlign:"right"},pending:{fontSize:9.5,color:colors.subtle,textAlign:"right",marginTop:2},ok:{fontSize:10,color:colors.success,textAlign:"right",marginTop:4},docButton:{backgroundColor:colors.navy,borderRadius:999,paddingHorizontal:13,paddingVertical:6},docButtonText:{color:"#FFF",fontSize:10.5,fontWeight:"700"},docDone:{backgroundColor:"#E8F7ED"},docDoneText:{color:colors.success,fontSize:10.5,fontWeight:"700"},add:{borderWidth:1.5,borderStyle:"dashed",borderColor:colors.navy,borderRadius:10,padding:12},addText:{color:colors.navy,fontWeight:"800",textAlign:"center"},primary:{backgroundColor:colors.navy,borderRadius:10,padding:14,flex:2},primaryText:{color:"#FFF",fontWeight:"800",textAlign:"center"},disabled:{opacity:.4},note:{fontSize:11,color:colors.subtle,lineHeight:18,textAlign:"right"},actions:{flexDirection:"row-reverse",gap:10},outline:{borderWidth:1.5,borderColor:colors.navy,borderRadius:10,padding:13,flex:1},outlineText:{color:colors.navy,fontWeight:"800",textAlign:"center"},line:{fontSize:12,color:colors.muted,textAlign:"right"}});
