import { useMemo,useState } from "react";
import { useLocalSearchParams } from "expo-router";
import { Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { colors } from "../../src/theme";
const META:Record<string,{title:string;fields:string[];note:string}>={
 flights:{title:"حجز الطيران",fields:["مدينة المغادرة","الوجهة","تاريخ السفر","تاريخ العودة (اختياري)","عدد المسافرين","الدرجة المفضلة","رقم الهاتف"],note:"سنراجع الرحلة والسعر والتوفر قبل تأكيد الدفع."},
 visas:{title:"التأشيرات",fields:["الدولة","نوع التأشيرة","الاسم حسب الجواز","رقم الجواز","الجنسية","تاريخ السفر المتوقع","رقم الهاتف"],note:"المتطلبات والسعر النهائي يعتمدان على نوع التأشيرة المنشور من الإدارة."},
 ferries:{title:"حجز البواخر",fields:["ميناء المغادرة","ميناء الوصول","تاريخ السفر","عدد المسافرين","شركة الباخرة (اختياري)","رقم الهاتف"],note:"سيتم تأكيد المقاعد والسعر بعد مراجعة الوكالة."},
 hotels:{title:"الفنادق والسياحة",fields:["المدينة / الوجهة","تاريخ الدخول","تاريخ الخروج","عدد النزلاء","عدد الغرف","ملاحظات","رقم الهاتف"],note:"نراجع التوفر ونرسل العرض قبل الدفع."},
 egypt:{title:"الموافقة الأمنية لمصر",fields:["الاسم حسب الجواز","رقم الجواز","الجنسية","تاريخ الميلاد","طريقة السفر (جوي / بري)","منفذ الوصول","رقم الهاتف"],note:"المستندات المطلوبة سترتبط بمتطلبات الخدمة المنشورة من الإدارة."},
 family:{title:"الزيارة العائلية السعودية",fields:["اسم مقدم الطلب","رقم الطلب / التأشيرة إن وجد","صلة القرابة","عدد الزوار","مرحلة المعاملة الحالية","رقم الهاتف"],note:"يمكن متابعة مراحل الطلب بعد إنشائه من صفحة طلباتي."}
};
export default function ServiceRequest(){const {kind}=useLocalSearchParams<{kind:string}>();const meta=META[kind??""]??{title:"طلب خدمة",fields:["الاسم","رقم الهاتف","ملاحظات"],note:"سيتم مراجعة الطلب من الوكالة."};const [values,setValues]=useState<Record<string,string>>({}),[review,setReview]=useState(false);const complete=useMemo(()=>meta.fields.filter(x=>!x.includes("اختياري")&&!x.includes("ملاحظات")).every(x=>values[x]?.trim()),[values,meta.fields]);if(review)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.title}>مراجعة {meta.title}</Text>{meta.fields.map(f=>values[f]?<View key={f} style={s.review}><Text style={s.label}>{f}</Text><Text style={s.value}>{values[f]}</Text></View>:null)}<Text style={s.note}>{meta.note}</Text><View style={s.actions}><Pressable style={s.outline} onPress={()=>setReview(false)}><Text style={s.outlineText}>تعديل</Text></Pressable><Pressable style={s.primary}><Text style={s.primaryText}>إرسال للوكالة</Text></Pressable></View></ScrollView></SafeAreaView>;return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.title}>{meta.title}</Text><Text style={s.desc}>{meta.note}</Text>{meta.fields.map(f=><View key={f}><Text style={s.label}>{f}</Text><TextInput value={values[f]??""} onChangeText={v=>setValues(x=>({...x,[f]:v}))} placeholder={f} style={s.input} textAlign="right" multiline={f==="ملاحظات"}/></View>)}<Pressable disabled={!complete} style={[s.primary,!complete&&s.disabled]} onPress={()=>setReview(true)}><Text style={s.primaryText}>مراجعة الطلب</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},page:{padding:20,gap:12,paddingBottom:40},title:{fontSize:20,fontWeight:"900",color:colors.navy,textAlign:"right"},desc:{fontSize:11.5,color:colors.muted,textAlign:"right",lineHeight:19},label:{fontSize:11,color:colors.muted,textAlign:"right",marginBottom:5},input:{backgroundColor:"#FFF",borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12,fontSize:12.5,minHeight:44},primary:{backgroundColor:colors.navy,borderRadius:10,padding:14,flex:2},primaryText:{color:"#FFF",fontWeight:"800",textAlign:"center"},disabled:{opacity:.4},review:{backgroundColor:"#FFF",borderWidth:1,borderColor:colors.border,borderRadius:10,padding:12},value:{fontSize:13,fontWeight:"700",color:colors.text,textAlign:"right"},note:{fontSize:11,color:colors.subtle,textAlign:"right",lineHeight:18},actions:{flexDirection:"row-reverse",gap:10},outline:{borderWidth:1.5,borderColor:colors.navy,borderRadius:10,padding:13,flex:1},outlineText:{color:colors.navy,fontWeight:"800",textAlign:"center"}});
