import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import prisma from "../../config/database.js";

const UPLOAD_DIR = path.resolve(process.env.UPLOAD_DIR || path.join(process.cwd(), "uploads", "flight-bookings"));
const STATUS_LABELS_AR = { REQUESTED: "تم استلام الطلب", RESERVATION_PENDING: "جاري الحجز المبدئي", PROVISIONAL_TICKET: "تم إصدار الحجز المبدئي", PAYMENT_PENDING: "بانتظار الدفع", PAYMENT_UNDER_REVIEW: "إشعار الدفع قيد المراجعة", PAYMENT_CONFIRMED: "تم تأكيد الدفع", FINAL_TICKET_ISSUED: "تم إصدار الحجز النهائي", CANCELLED: "ملغي" };
function bookingNumber() { return `FLT-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(2).toString("hex").toUpperCase()}`; }
function safeName(name) { return String(name || "file").replace(/[^a-zA-Z0-9._-]/g, "_"); }
function normalizePhone(value) { return String(value || "").replace(/[^0-9+]/g, "").replace(/^00/, "+"); }
async function saveFile(file, bookingNumberValue, prefix) { if (!file) throw new Error("File is required"); await fs.mkdir(path.join(UPLOAD_DIR, bookingNumberValue), { recursive: true }); const filename = `${prefix}-${Date.now()}-${safeName(file.originalname)}`; const fullPath = path.join(UPLOAD_DIR, bookingNumberValue, filename); await fs.writeFile(fullPath, file.buffer); return { path: path.relative(process.cwd(), fullPath), name: file.originalname }; }
async function ensureOrderAndCustomer(input) { let customer = input.customerId ? await prisma.customer.findUnique({ where: { id: input.customerId } }) : null; if (!customer) { const passportNo = String(input.contact?.passportNo || input.passengers?.[0]?.passportNo || "").trim(); if (passportNo) customer = await prisma.customer.findUnique({ where: { passportNo } }); } if (!customer) { const passportNo = `${String(input.contact?.passportNo || input.passengers?.[0]?.passportNo || "TEMP-")}-${Date.now()}`; customer = await prisma.customer.create({ data: { customerNo: `CUS-${Date.now().toString(36).toUpperCase()}`, fullName: String(input.contact?.fullName || `${input.passengers?.[0]?.firstName || ""} ${input.passengers?.[0]?.lastName || ""}`).trim(), passportNo, nationality: String(input.passengers?.[0]?.nationality || "UNKNOWN").trim(), birthDate: input.passengers?.[0]?.birthDate ? new Date(input.passengers[0].birthDate) : null, gender: input.passengers?.[0]?.gender || null, phone: input.contact?.phone || null, email: input.contact?.email || null } }); } const order = await prisma.order.create({ data: { orderNumber: `ORD-${Date.now().toString(36).toUpperCase()}`, customerId: customer.id, status: "NEW", paymentStatus: "UNPAID", totalAmount: Number(input.amount || 0), currency: input.currency || "SDG" } }); return { customer, order }; }
export async function createFlightBooking(input) { const flightIds = Array.isArray(input.flightIds) && input.flightIds.length ? input.flightIds.map(String) : input.flightId ? [String(input.flightId)] : []; if (!flightIds.length) throw new Error("At least one flight is required"); if (!Array.isArray(input.passengers) || !input.passengers.length) throw new Error("At least one passenger is required"); if (!input.contact?.phone) throw new Error("Phone is required"); const amount = Number(input.amount); if (!Number.isFinite(amount) || amount <= 0) throw new Error("Valid booking amount is required"); const { customer, order } = await ensureOrderAndCustomer({ ...input, amount }); const id = crypto.randomUUID(); const number = bookingNumber(); await prisma.$executeRawUnsafe(`INSERT INTO flight_bookings (id,booking_number,order_id,customer_id,flight_id,status,passengers,amount,currency,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,'REQUESTED',$6::jsonb,$7,$8,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`, id, number, order.id, customer.id, JSON.stringify(flightIds), JSON.stringify(input.passengers), amount, input.currency || "SDG"); return getFlightBooking(id); }
export async function getFlightBooking(idOrNumber) { const rows = await prisma.$queryRawUnsafe(`SELECT fb.*, c."fullName" AS customer_name, c.phone AS customer_phone, c.email AS customer_email FROM flight_bookings fb JOIN "Customer" c ON c.id=fb.customer_id WHERE fb.id=$1 OR fb.booking_number=$1 LIMIT 1`, idOrNumber); if (!rows[0]) return null; const booking = rows[0]; let flightIds = []; try { flightIds = JSON.parse(String(booking.flight_id || "[]")); if (!Array.isArray(flightIds)) flightIds = [String(booking.flight_id)]; } catch { flightIds = booking.flight_id ? [String(booking.flight_id)] : []; } return { ...booking, flightIds, statusLabel: STATUS_LABELS_AR[booking.status] || booking.status }; }
export async function getPublicFlightBooking(idOrNumber, phone) { const booking = await getFlightBooking(idOrNumber); if (!booking || !phone || normalizePhone(phone) !== normalizePhone(booking.customer_phone)) return null; const accounts = ["PAYMENT_PENDING", "PAYMENT_UNDER_REVIEW", "PAYMENT_CONFIRMED"].includes(booking.status) ? await getBankAccounts() : []; return { ...booking, bankAccounts: accounts }; }
export async function listFlightBookings(status) { const rows = await prisma.$queryRawUnsafe(`SELECT fb.*, c."fullName" AS customer_name, c.phone AS customer_phone FROM flight_bookings fb JOIN "Customer" c ON c.id=fb.customer_id ${status ? "WHERE fb.status=$1" : ""} ORDER BY fb.created_at DESC LIMIT 200`, ...(status ? [status] : [])); return Promise.all(rows.map(async (row) => ({ ...(await getFlightBooking(row.id)), statusLabel: STATUS_LABELS_AR[row.status] || row.status }))); }
export async function uploadProvisionalTicket(id, file) { const booking = await getFlightBooking(id); if (!booking) throw new Error("Booking not found"); if (!["REQUESTED", "RESERVATION_PENDING"].includes(booking.status)) throw new Error("Provisional ticket can only be uploaded for a new booking"); const saved = await saveFile(file, booking.booking_number, "provisional-ticket"); await prisma.$executeRawUnsafe(`UPDATE flight_bookings SET status='PAYMENT_PENDING', provisional_ticket_path=$2, provisional_ticket_name=$3, provisional_ticket_uploaded_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE id=$1`, booking.id, saved.path, saved.name); await prisma.order.update({ where: { id: booking.order_id }, data: { status: "PROCESSING", paymentStatus: "UNPAID" } }); return getFlightBooking(booking.id); }
export async function submitPaymentReceipt(id, file, phone) { const booking = await getFlightBooking(id); if (!booking) throw new Error("Booking not found"); if (!phone || normalizePhone(phone) !== normalizePhone(booking.customer_phone)) throw new Error("بيانات التحقق غير صحيحة"); if (booking.status !== "PAYMENT_PENDING") throw new Error("لا يمكن رفع إشعار الدفع في هذه المرحلة"); if (!(await getBankAccounts()).length) throw new Error("لا يوجد حساب دفع نشط حاليًا"); const saved = await saveFile(file, booking.booking_number, "payment-receipt"); await prisma.$executeRawUnsafe(`UPDATE flight_bookings SET status='PAYMENT_UNDER_REVIEW', payment_receipt_path=$2, payment_receipt_name=$3, payment_receipt_uploaded_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE id=$1`, booking.id, saved.path, saved.name); return getFlightBooking(booking.id); }
export async function confirmPayment(id, userId, note) { const booking = await getFlightBooking(id); if (!booking) throw new Error("Booking not found"); if (booking.status !== "PAYMENT_UNDER_REVIEW") throw new Error("Payment receipt must be reviewed before confirmation"); await prisma.$executeRawUnsafe(`UPDATE flight_bookings SET status='PAYMENT_CONFIRMED', payment_review_note=$2, updated_at=CURRENT_TIMESTAMP WHERE id=$1`, booking.id, note || null); await prisma.payment.create({ data: { orderId: booking.order_id, amount: booking.amount, currency: booking.currency, paymentMethod: "BANK_TRANSFER", status: "PAID", paidAt: new Date() } }); await prisma.order.update({ where: { id: booking.order_id }, data: { status: "PROCESSING", paymentStatus: "PAID" } }); return getFlightBooking(booking.id); }
export async function issueFinalTicket(id, file) { const booking = await getFlightBooking(id); if (!booking) throw new Error("Booking not found"); if (booking.status !== "PAYMENT_CONFIRMED") throw new Error("Payment must be confirmed before final ticket issuance"); const saved = await saveFile(file, booking.booking_number, "final-ticket"); await prisma.$executeRawUnsafe(`UPDATE flight_bookings SET status='FINAL_TICKET_ISSUED', final_ticket_path=$2, final_ticket_name=$3, final_ticket_uploaded_at=CURRENT_TIMESTAMP, updated_at=CURRENT_TIMESTAMP WHERE id=$1`, booking.id, saved.path, saved.name); await prisma.order.update({ where: { id: booking.order_id }, data: { status: "COMPLETED" } }); return getFlightBooking(booking.id); }
export async function getBankAccounts() { return prisma.$queryRawUnsafe(`SELECT id,key,label,account_number,bank_name,active FROM flight_bank_accounts WHERE active=true ORDER BY label`); }
export async function upsertBankAccount(input) { if (!input.key || !input.label || !input.accountNumber) throw new Error("key, label and accountNumber are required"); const id = input.id || crypto.randomUUID(); await prisma.$executeRawUnsafe(`INSERT INTO flight_bank_accounts (id,key,label,account_number,bank_name,active) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (key) DO UPDATE SET label=EXCLUDED.label,account_number=EXCLUDED.account_number,bank_name=EXCLUDED.bank_name,active=EXCLUDED.active,updated_at=CURRENT_TIMESTAMP`, id, input.key, input.label, input.accountNumber, input.bankName || null, input.active !== false); return (await prisma.$queryRawUnsafe(`SELECT id,key,label,account_number,bank_name,active FROM flight_bank_accounts WHERE key=$1 LIMIT 1`, input.key))[0]; }
export async function getBookingFile(idOrNumber, kind) { const booking = await getFlightBooking(idOrNumber); if (!booking) throw new Error("Booking not found"); const field = kind === "provisional" ? "provisional_ticket_path" : kind === "receipt" ? "payment_receipt_path" : kind === "final" ? "final_ticket_path" : null; if (!field || !booking[field]) throw new Error("File not available"); const absolute = path.resolve(process.cwd(), booking[field]); if (!absolute.startsWith(UPLOAD_DIR)) throw new Error("Invalid file path"); return { path: absolute, name: booking[field.replace("_path", "_name")] || path.basename(absolute) }; }
