-- Adds CaseNote only. This migration was generated by `prisma migrate dev`
-- against a database that still has the `flight_bank_accounts`,
-- `flight_bookings` and `flight_inventory` tables (created by the
-- 20260822000000_flight_booking_workflow / 20260822090000_flight_inventory
-- migrations) even though those models are no longer declared in
-- schema.prisma. Prisma's auto-diff proposed DROPping all three live
-- tables to reconcile that drift — a pre-existing, undocumented gap
-- between schema.prisma and migration history, not something this change
-- introduces or needs. The DROP TABLE/DROP CONSTRAINT statements for those
-- three tables have been deliberately removed from this file: dropping
-- them is a real, separate, irreversible data-loss decision that needs its
-- own reviewed migration (with a data export first, if Production has any
-- rows in them) — never bundled silently into an unrelated feature.
--
-- CreateTable
CREATE TABLE "CaseNote" (
    "id" TEXT NOT NULL,
    "contactRequestId" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "authorUserId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CaseNote_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "CaseNote_contactRequestId_idx" ON "CaseNote"("contactRequestId");

-- AddForeignKey
ALTER TABLE "CaseNote" ADD CONSTRAINT "CaseNote_contactRequestId_fkey" FOREIGN KEY ("contactRequestId") REFERENCES "ContactRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CaseNote" ADD CONSTRAINT "CaseNote_authorUserId_fkey" FOREIGN KEY ("authorUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
