import { useCallback,useEffect,useState } from "react";
import { router } from "expo-router";
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from "react-native";
import { AdminRequest,getAdminRequests,getOperationsCenter } from "../../src/api/admin";
import { colors } from "../../src/theme";

export default function AdminScreen(){
 const [loading,setLoading]=useState(true),[error,setError]=useState(""),[items,setItems]=useState<AdminRequest[]>([]),[ops,setOps]=useState<any>(null);
 const load=useCallback(async()=>{try{setLoading(true);setError("");const [requests,operations]=await Promise.all([getAdminRequests(),getOperationsCenter()]);setItems(requests);setOps(operations);}catch(e){setError("تعذر تحميل الإدارة. سجل الدخول بحساب موظف صالح.");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 if(loading)return <View style={s.center}><ActivityIndicator color={colors.navy}/><Text>جاري تحميل لوحة الإدارة…</Text></View>;
 if(error)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.error}>{error}</Text><Pressable style={s.primary} onPress={()=>router.replace("/admin/login")}><Text style={s.primaryText}>تسجيل دخول الإدارة</Text></Pressable></View></SafeAreaView>;
 const queues=ops?.queues??ops?.data?.queues??{};
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><View style={s.head}><View><Text style={s.title}>لوحة الإدارة</Text><Text style={s.desc}>الطلبات والعمليات الحالية</Text></View><Pressable onPress={()=>void load()}><Text style={s.link}>تحديث</Text></Pressable></View><View style={s.stats}><Stat label="الطلبات" value={items.length}/><Stat label="مراجعة مستندات" value={queues.NEEDS_REVIEW??0}/><Stat label="بانتظار دفع" value={queues.WAITING_PAYMENT??0}/></View><View style={s.manage}><Pressable style={s.manageCard} onPress={()=>router.push("/admin/catalog")}><Text style={s.manageTitle}>الخدمات والأسعار</Text><Text style={s.manageDesc}>تعديل أسعار الخدمات والتأشيرات وحالتها</Text></Pressable><Pressable style={s.manageCard} onPress={()=>router.push("/admin/rates")}><Text style={s.manageTitle}>أسعار الصرف</Text><Text style={s.manageDesc}>USD / SAR / AED / EGP مقابل SDG</Text></Pressable></View><Text style={s.section}>آخر الطلبات</Text>{items.map(item=><Pressable key={item.id} style={s.card} onPress={()=>router.push({pathname:"/admin/request/[id]",params:{id:item.id}})}><View style={s.row}><Text style={s.cardTitle}>{item.service??"طلب خدمة"}</Text><Text style={s.badge}>{item.readiness?.queue??item.status}</Text></View><Text style={s.name}>{item.name}</Text><Text style={s.meta}>{item.phone} · {item.id}</Text>{item.paymentStatus&&<Text style={s.payment}>الدفع: {item.paymentStatus}</Text>}</Pressable>)}</ScrollView></SafeAreaView>;
}
function Stat({label,value}:{label:string;value:any}){return <View style={s.stat}><Text style={s.statValue}>{String(value)}</Text><Text style={s.statLabel}>{label}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},page:{padding:18,gap:11,paddingBottom:40},center:{flex:1,alignItems:"center",justifyContent:"center",gap:12,padding:24},head:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center"},title:{fontSize:21,fontWeight:"900",color:colors.navy,textAlign:"right"},desc:{fontSize:11,color:colors.muted,textAlign:"right"},link:{color:colors.navy,fontWeight:"800"},stats:{flexDirection:"row-reverse",gap:8},stat:{flex:1,backgroundColor:"#FFF",borderWidth:1,borderColor:colors.border,borderRadius:12,padding:12,alignItems:"flex-end"},statValue:{fontSize:19,fontWeight:"900",color:colors.navy},statLabel:{fontSize:9.5,color:colors.muted,textAlign:"right"},section:{fontSize:14,fontWeight:"900",color:colors.text,textAlign:"right",marginTop:4},manage:{flexDirection:"row-reverse",gap:8},manageCard:{flex:1,backgroundColor:"#FFF",borderWidth:1,borderColor:colors.border,borderRadius:12,padding:12},manageTitle:{fontSize:11.5,fontWeight:"900",color:colors.navy,textAlign:"right"},manageDesc:{fontSize:9.5,color:colors.muted,textAlign:"right",marginTop:4,lineHeight:15},card:{backgroundColor:"#FFF",borderWidth:1,borderColor:colors.border,borderRadius:13,padding:14,gap:5},row:{flexDirection:"row-reverse",justifyContent:"space-between",alignItems:"center",gap:8},cardTitle:{fontSize:13,fontWeight:"800",color:colors.text,textAlign:"right",flex:1},badge:{fontSize:8.5,color:colors.navy,backgroundColor:"#EEF3FB",paddingHorizontal:8,paddingVertical:4,borderRadius:999},name:{fontSize:11.5,color:colors.muted,textAlign:"right"},meta:{fontSize:9.5,color:colors.subtle,textAlign:"right"},payment:{fontSize:10,color:colors.gold,textAlign:"right",fontWeight:"700"},primary:{backgroundColor:colors.navy,borderRadius:10,padding:13},primaryText:{color:"#FFF",fontWeight:"800",textAlign:"center"},error:{color:colors.danger,textAlign:"center",lineHeight:20}});
