"use client";
/* eslint-disable react-hooks/set-state-in-effect -- initial data loading synchronizes with the API. */

import * as React from "react";
import { Check, Loader2, RefreshCw, UserRoundCog } from "lucide-react";
import { Button } from "@/components/ui/button";
import { adminRequest } from "@/lib/admin-api";

type Staff = { id: string; fullName: string; employeeNo: string; role: string; status: string };
type Order = { id: string; orderNumber: string; status: string; assignedUserId?: string | null; customer?: { fullName: string } | null; service?: { name: string } | null; createdAt: string };

export function AssignmentsManager() {
  const [orders, setOrders] = React.useState<Order[]>([]); const [staff, setStaff] = React.useState<Staff[]>([]); const [loading, setLoading] = React.useState(true); const [working, setWorking] = React.useState<string | null>(null); const [error, setError] = React.useState(""); const [success, setSuccess] = React.useState("");
  async function load() { setLoading(true); setError(""); try { const [ordersPayload, staffPayload] = await Promise.all([adminRequest<{ data: Order[] }>("/orders?limit=100"), adminRequest<{ data: Staff[] }>("/users")]); setOrders(ordersPayload.data || []); setStaff((staffPayload.data || []).filter((item) => item.status === "ACTIVE")); } catch (err) { setError(err instanceof Error ? err.message : "تعذر تحميل الإسنادات"); } finally { setLoading(false); } }
  React.useEffect(() => { void load(); }, []);
  async function assign(order: Order, assignedUserId: string) { setWorking(order.id); setError(""); setSuccess(""); try { const payload = await adminRequest<{ data: Order }>(`/orders/${order.id}/assign`, { method: "PATCH", body: JSON.stringify({ assignedUserId: assignedUserId || null }) }); setOrders((current) => current.map((item) => item.id === order.id ? { ...item, ...payload.data } : item)); setSuccess(`تم إسناد ${order.orderNumber}`); } catch (err) { setError(err instanceof Error ? err.message : "تعذر إسناد الطلب"); } finally { setWorking(null); } }
  return <section className="mx-auto max-w-7xl space-y-5 px-4 py-7 sm:px-6 lg:px-10">{error ? <div className="rounded-2xl border border-destructive/20 bg-destructive/5 p-4 text-sm font-bold text-destructive">{error}</div> : null}{success ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700"><Check className="me-2 inline size-4" />{success}</div> : null}<div className="flex items-center justify-between rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="flex items-start gap-3"><div className="flex size-11 items-center justify-center rounded-2xl bg-primary/10 text-primary"><UserRoundCog className="size-5" /></div><div><h2 className="text-xl font-black">إسناد الطلبات</h2><p className="mt-1 text-sm leading-7 text-muted-foreground">عرض الطلبات التي يسمح بها RBAC وإسنادها إلى موظف نشط عبر business rule الحالي.</p></div></div><Button type="button" variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "size-4 animate-spin" : "size-4"} />تحديث</Button></div><div className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground"><th className="px-3 py-3 text-start">الطلب</th><th className="px-3 py-3 text-start">العميل</th><th className="px-3 py-3 text-start">الخدمة</th><th className="px-3 py-3 text-start">الحالة</th><th className="px-3 py-3 text-start">الموظف المسند</th></tr></thead><tbody>{loading ? <tr><td colSpan={5} className="px-3 py-10 text-center text-muted-foreground">جاري التحميل...</td></tr> : null}{orders.map((order) => <tr key={order.id} className="border-b border-border/70"><td className="px-3 py-4 font-mono font-bold" dir="ltr">{order.orderNumber}</td><td className="px-3 py-4">{order.customer?.fullName || "عميل"}</td><td className="px-3 py-4">{order.service?.name || "—"}</td><td className="px-3 py-4">{order.status}</td><td className="px-3 py-4"><div className="flex items-center gap-2"><select value={order.assignedUserId || ""} disabled={working === order.id} onChange={(e) => void assign(order, e.target.value)} className="h-9 min-w-52 rounded-lg border border-border bg-background px-2 text-xs font-bold"><option value="">غير مسند</option>{staff.map((member) => <option key={member.id} value={member.id}>{member.fullName} · {member.employeeNo}</option>)}</select>{working === order.id ? <Loader2 className="size-4 animate-spin" /> : null}</div></td></tr>)}</tbody></table></div></div></section>;
}
