"use client";
/* eslint-disable react-hooks/set-state-in-effect -- initial data loading synchronizes with the API. */

import * as React from "react";
import { FileCheck2, RefreshCw, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { adminRequest } from "@/lib/admin-api";

type DocumentRow = { id: string; fileName: string; documentType?: string | null; mimeType: string; sizeBytes: number; createdAt: string; status?: string | null; reviewStatus?: string | null; customer?: { fullName: string } | null; order?: { orderNumber: string } | null };

export function DocumentsManager() {
  const [documents, setDocuments] = React.useState<DocumentRow[]>([]); const [query, setQuery] = React.useState(""); const [loading, setLoading] = React.useState(true); const [error, setError] = React.useState("");
  async function load() { setLoading(true); setError(""); try { const payload = await adminRequest<{ data: DocumentRow[] }>("/documents?limit=100"); setDocuments(payload.data || []); } catch (err) { setError(err instanceof Error ? err.message : "تعذر تحميل المستندات"); } finally { setLoading(false); } }
  React.useEffect(() => { void load(); }, []);
  const filtered = documents.filter((item) => [item.fileName, item.documentType || "", item.customer?.fullName || "", item.order?.orderNumber || ""].some((value) => value.toLowerCase().includes(query.trim().toLowerCase())));
  return <section className="mx-auto max-w-7xl space-y-5 px-4 py-7 sm:px-6 lg:px-10">{error ? <div className="rounded-2xl border border-destructive/20 bg-destructive/5 p-4 text-sm font-bold text-destructive">{error}</div> : null}<div className="flex items-center justify-between rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="flex items-start gap-3"><div className="flex size-11 items-center justify-center rounded-2xl bg-primary/10 text-primary"><FileCheck2 className="size-5" /></div><div><h2 className="text-xl font-black">مستندات العملاء</h2><p className="mt-1 text-sm leading-7 text-muted-foreground">قائمة metadata تشغيلية. فتح الملف أو تنزيله يبقى خلف ownership والـauthorization في المسارات المتخصصة.</p></div></div><Button type="button" variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "size-4 animate-spin" : "size-4"} />تحديث</Button></div><div className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="relative max-w-xl"><Search className="pointer-events-none absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="بحث باسم الملف أو العميل أو رقم الطلب" className="h-11 w-full rounded-xl border border-border bg-background ps-10 pe-3 text-sm outline-none focus:border-primary" /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground"><th className="px-3 py-3 text-start">الملف</th><th className="px-3 py-3 text-start">العميل</th><th className="px-3 py-3 text-start">الطلب</th><th className="px-3 py-3 text-start">النوع</th><th className="px-3 py-3 text-start">الحالة</th><th className="px-3 py-3 text-start">التاريخ</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="px-3 py-10 text-center text-muted-foreground">جاري التحميل...</td></tr> : null}{filtered.map((item) => <tr key={item.id} className="border-b border-border/70"><td className="px-3 py-4"><p className="max-w-64 truncate font-bold">{item.fileName}</p><p className="text-xs text-muted-foreground">{item.mimeType} · {Math.round(item.sizeBytes / 1024)} KB</p></td><td className="px-3 py-4">{item.customer?.fullName || "—"}</td><td className="px-3 py-4 font-mono text-xs" dir="ltr">{item.order?.orderNumber || "—"}</td><td className="px-3 py-4">{item.documentType || "—"}</td><td className="px-3 py-4">{item.reviewStatus || item.status || "مستلم"}</td><td className="px-3 py-4 text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleDateString("ar-SA")}</td></tr>)}</tbody></table></div></div></section>;
}
