"use client";
/* eslint-disable react-hooks/set-state-in-effect, @next/next/no-img-element -- API-backed public asset URLs are dynamic. */

import * as React from "react";
import { Check, ImagePlus, Loader2, Search, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { API_URL } from "@/lib/api-url";
import { adminAssetUrl, adminRequest } from "@/lib/admin-api";

type Asset = { id: string; key: string; fileName: string; storagePath: string; mimeType: string; sizeBytes: number; updatedAt: string };
const assetKeys = ["logo", "logo-dark", "icon-umrah", "icon-visa", "icon-flight", "icon-hotel", "icon-international", "icon-packages", "favicon", "hero-image"] as const;

export function MediaManager() {
  const [assets, setAssets] = React.useState<Asset[]>([]); const [query, setQuery] = React.useState(""); const [key, setKey] = React.useState(""); const [file, setFile] = React.useState<File | null>(null); const [loading, setLoading] = React.useState(true); const [working, setWorking] = React.useState(false); const [error, setError] = React.useState(""); const [success, setSuccess] = React.useState("");
  async function load() { setLoading(true); setError(""); try { const payload = await adminRequest<{ data: Asset[] }>("/site-assets"); setAssets(payload.data || []); } catch (err) { setError(err instanceof Error ? err.message : "تعذر تحميل الوسائط"); } finally { setLoading(false); } }
  React.useEffect(() => { void load(); }, []);
  async function upload(event: React.FormEvent) { event.preventDefault(); if (!key.trim() || !file) { setError("اختر مفتاحًا وملفًا قبل الرفع"); return; } setWorking(true); setError(""); setSuccess(""); const formData = new FormData(); formData.append("file", file); try { const response = await fetch(`${API_URL}/site-assets/${encodeURIComponent(key.trim())}`, { method: "POST", credentials: "include", body: formData }); const payload = await response.json().catch(() => null); if (!response.ok || !payload?.success) throw new Error(payload?.message || "تعذر رفع الوسيط"); setAssets((current) => [payload.data, ...current.filter((item) => item.key !== payload.data.key)]); setKey(""); setFile(null); setSuccess("تم رفع الوسيط وتحديث المرجع"); } catch (err) { setError(err instanceof Error ? err.message : "تعذر رفع الوسيط"); } finally { setWorking(false); } }
  const filtered = assets.filter((asset) => [asset.key, asset.fileName, asset.mimeType].some((value) => value.toLowerCase().includes(query.trim().toLowerCase())));
  return <section className="mx-auto max-w-7xl space-y-5 px-4 py-7 sm:px-6 lg:px-10">{error ? <div className="rounded-2xl border border-destructive/20 bg-destructive/5 p-4 text-sm font-bold text-destructive">{error}</div> : null}{success ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700"><Check className="me-2 inline size-4" />{success}</div> : null}<div className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="flex items-start gap-3"><div className="flex size-11 items-center justify-center rounded-2xl bg-primary/10 text-primary"><ImagePlus className="size-5" /></div><div><h2 className="text-xl font-black">مكتبة الوسائط</h2><p className="mt-1 text-sm leading-7 text-muted-foreground">هذه المكتبة مخصصة للأصول العامة فقط. المستندات الخاصة لا تستخدم روابط SiteAsset العامة.</p></div></div><form onSubmit={upload} className="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><select required value={key} onChange={(e) => setKey(e.target.value)} className="h-11 rounded-xl border border-border bg-background px-3 text-sm"><option value="">اختر موضع الوسيط</option>{assetKeys.map((assetKey) => <option key={assetKey} value={assetKey}>{assetKey}</option>)}</select><input required type="file" accept="image/*" onChange={(e) => setFile(e.target.files?.[0] || null)} className="h-11 rounded-xl border border-border bg-background px-3 py-2 text-sm" /><Button type="submit" disabled={working}>{working ? <Loader2 className="size-4 animate-spin" /> : <Upload className="size-4" />}رفع أو استبدال</Button></form></div><div className="rounded-3xl border border-border bg-card p-5 shadow-sm sm:p-7"><div className="relative max-w-xl"><Search className="pointer-events-none absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="بحث بالمفتاح أو اسم الملف" className="h-11 w-full rounded-xl border border-border bg-background ps-10 pe-3 text-sm outline-none focus:border-primary" /></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{loading ? <p className="col-span-full py-10 text-center text-muted-foreground">جاري التحميل...</p> : null}{filtered.map((asset) => <div key={asset.id} className="overflow-hidden rounded-2xl border border-border"><div className="aspect-video bg-muted">{asset.mimeType.startsWith("image/") ? <img src={`${adminAssetUrl(asset.key)}?v=${encodeURIComponent(asset.updatedAt)}`} alt={asset.fileName} className="size-full object-cover" /> : null}</div><div className="p-4"><p className="font-mono text-sm font-bold" dir="ltr">{asset.key}</p><p className="mt-1 truncate text-xs text-muted-foreground">{asset.fileName}</p><p className="mt-2 text-xs text-muted-foreground">{Math.round(asset.sizeBytes / 1024)} KB · {asset.mimeType}</p></div></div>)}</div></div></section>;
}
