import { useCallback,useEffect,useState } from "react";
import { useLocalSearchParams } from "expo-router";
import { ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { AdminRequest,confirmAdminPayment,getAdminRequests,reviewAdminDocument,updateAdminRequestStatus } from "../../../src/api/admin";
import { CaseNote,addCaseNote,getCaseNotes } from "../../../src/api/notes";
import { colors } from "../../../src/theme";

export default function AdminRequestDetail(){
 const {id}=useLocalSearchParams<{id:string}>();
 const [item,setItem]=useState<AdminRequest|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false),[rejecting,setRejecting]=useState<string|null>(null),[note,setNote]=useState("");
 const load=useCallback(async()=>{try{setError("");const found=(await getAdminRequests()).find(x=>x.id===id)??null;setItem(found);if(!found)setError("الطلب غير موجود في القائمة الحالية.");}catch{setError("تعذر تحميل الطلب.");}finally{setLoading(false);}},[id]);
 useEffect(()=>{void load();},[load]);
 async function act(fn:()=>Promise<unknown>){try{setBusy(true);setError("");await fn();setRejecting(null);setNote("");await load();}catch(e){setError(e instanceof Error?e.message:"تعذر تنفيذ العملية");}finally{setBusy(false);}}
 if(loading)return <View style={s.center}><ActivityIndicator color={colors.navy}/></View>;
 if(!item)return <SafeAreaView style={s.safe}><View style={s.center}><Text style={s.error}>{error||"الطلب غير موجود"}</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}><Text style={s.title}>{item.service??"طلب خدمة"}</Text><Text style={s.id}>{item.id}</Text><Info label="العميل" value={item.name}/><Info label="الهاتف" value={item.phone}/><Info label="الحالة" value={item.status}/><Info label="الدفع" value={item.paymentStatus??"—"}/>{item.invoice&&<Info label="الفاتورة" value={`${item.invoice.amount} ${item.invoice.currency} · ${item.invoice.status}`}/>}
 <View style={s.actions}>{item.status==="NEW"&&<Pressable style={s.primary} disabled={busy} onPress={()=>act(()=>updateAdminRequestStatus(item.id,"CONTACTED"))}><Text style={s.primaryText}>تم التواصل</Text></Pressable>}{item.status!=="CLOSED"&&<Pressable style={s.success} disabled={busy} onPress={()=>act(()=>updateAdminRequestStatus(item.id,"CLOSED","COMPLETED"))}><Text style={s.successText}>إكمال الطلب</Text></Pressable>}{item.paymentStatus==="UNDER_REVIEW"&&<Pressable style={s.gold} disabled={busy} onPress={()=>act(()=>confirmAdminPayment(item.id))}><Text style={s.goldText}>تأكيد الدفع</Text></Pressable>}</View>
 {!!item.travelers?.length&&<View style={s.section}><Text style={s.sectionTitle}>المسافرون</Text>{item.travelers.map((t,i)=><View key={t.id} style={s.row}><Text style={s.rowTitle}>{i+1}. {t.fullName}</Text><Text style={s.small}>{t.passportNo??""} {t.nationality??""}</Text></View>)}</View>}
 <View style={s.section}><Text style={s.sectionTitle}>المستندات</Text>{!item.documents?.length?<Text style={s.small}>لا توجد مستندات.</Text>:item.documents.map(d=><View key={d.id} style={s.doc}><View style={s.docHead}><Text style={s.rowTitle}>{d.label??d.fileName??"مستند"}</Text><Text style={s.badge}>{d.status??"PENDING"}</Text></View>{d.status==="PENDING"&&<View style={s.actions}><Pressable style={s.outline} disabled={busy} onPress={()=>{setRejecting(d.id);setNote("");}}><Text style={s.rejectText}>رفض</Text></Pressable><Pressable style={s.primary} disabled={busy} onPress={()=>act(()=>reviewAdminDocument(item.id,d.id,"ACCEPTED"))}><Text style={s.primaryText}>قبول</Text></Pressable></View>}{rejecting===d.id&&<View style={s.rejectBox}><TextInput value={note} onChangeText={setNote} placeholder="سبب الرفض للعميل" style={s.input} textAlign="right"/><Pressable disabled={note.trim().length<2||busy} style={[s.rejectBtn,(note.trim().length<2||busy)&&s.disabled]} onPress={()=>act(()=>reviewAdminDocument(item.id,d.id,"REJECTED",note))}><Text style={s.rejectBtnText}>تأكيد الرفض</Text></Pressable></View>}</View>)}</View>
 <NotesSection requestId={item.id}/>
 {!!error&&<Text style={s.error}>{error}</Text>}</ScrollView></SafeAreaView>;
}
function NotesSection({requestId}:{requestId:string}){
 const [notes,setNotes]=useState<CaseNote[]>([]),[loading,setLoading]=useState(true),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{try{setNotes(await getCaseNotes(requestId));}catch{setError("تعذر تحميل الملاحظات.");}finally{setLoading(false);}},[requestId]);
 useEffect(()=>{void load();},[load]);
 async function submit(){if(draft.trim().length<2)return;try{setBusy(true);setError("");await addCaseNote(requestId,draft.trim());setDraft("");await load();}catch(e){setError(e instanceof Error?e.message:"تعذر إضافة الملاحظة");}finally{setBusy(false);}}
 return <View style={s.section}><Text style={s.sectionTitle}>ملاحظات داخلية</Text><Text style={s.small}>للفريق فقط، لا تظهر للعميل أبدًا.</Text><TextInput value={draft} onChangeText={setDraft} placeholder="اكتب ملاحظة عن هذه الحالة..." style={s.input} textAlign="right" multiline/><Pressable disabled={draft.trim().length<2||busy} style={[s.primary,(draft.trim().length<2||busy)&&s.disabled]} onPress={submit}><Text style={s.primaryText}>{busy?"جارٍ الإضافة...":"إضافة ملاحظة"}</Text></Pressable>{!!error&&<Text style={s.error}>{error}</Text>}{loading?<Text style={s.small}>جاري تحميل الملاحظات…</Text>:!notes.length?<Text style={s.small}>لا توجد ملاحظات على هذه الحالة بعد.</Text>:notes.map(n=><View key={n.id} style={s.row}><Text style={s.rowTitle}>{n.body}</Text><Text style={s.small}>{n.author?.fullName??""} · {new Date(n.createdAt).toLocaleString("ar",{calendar:"gregory",day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</Text></View>)}</View>;
}
function Info({label,value}:{label:string;value:string}){return <View style={s.info}><Text style={s.label}>{label}</Text><Text style={s.value}>{value}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},page:{padding:18,gap:10,paddingBottom:40},center:{flex:1,justifyContent:"center",alignItems:"center"},title:{fontSize:20,fontWeight:"900",color:colors.navy,textAlign:"right"},id:{fontFamily:"monospace",fontSize:10,color:colors.subtle,textAlign:"right"},info:{backgroundColor:"#FFF",borderWidth:1,borderColor:colors.border,borderRadius:10,padding:11,flexDirection:"row-reverse",justifyContent:"space-between",gap:8},label:{fontSize:10.5,color:colors.muted},value:{fontSize:11.5,fontWeight:"700",color:colors.text,textAlign:"right",flex:1},actions:{flexDirection:"row-reverse",gap:8,flexWrap:"wrap"},primary:{backgroundColor:colors.navy,borderRadius:9,paddingHorizontal:12,paddingVertical:10,flex:1},primaryText:{color:"#FFF",fontWeight:"800",textAlign:"center",fontSize:11},success:{backgroundColor:"#E8F7ED",borderRadius:9,paddingHorizontal:12,paddingVertical:10,flex:1},successText:{color:colors.success,fontWeight:"800",textAlign:"center",fontSize:11},gold:{backgroundColor:"#FFF8E1",borderRadius:9,paddingHorizontal:12,paddingVertical:10,flex:1},goldText:{color:"#9A7200",fontWeight:"800",textAlign:"center",fontSize:11},section:{backgroundColor:"#FFF",borderWidth:1,borderColor:colors.border,borderRadius:13,padding:13,gap:8},sectionTitle:{fontSize:13,fontWeight:"900",color:colors.text,textAlign:"right"},row:{borderBottomWidth:1,borderBottomColor:colors.border,paddingVertical:7},rowTitle:{fontSize:11.5,fontWeight:"700",color:colors.text,textAlign:"right"},small:{fontSize:10,color:colors.muted,textAlign:"right",marginTop:3},doc:{backgroundColor:colors.soft,borderRadius:10,padding:10,gap:8},docHead:{flexDirection:"row-reverse",justifyContent:"space-between"},badge:{fontSize:9,color:colors.navy},outline:{borderWidth:1,borderColor:colors.danger,borderRadius:9,paddingHorizontal:12,paddingVertical:10,flex:1},rejectText:{color:colors.danger,fontWeight:"800",textAlign:"center",fontSize:11},rejectBox:{gap:8},input:{backgroundColor:"#FFF",borderWidth:1,borderColor:colors.border,borderRadius:9,padding:10},rejectBtn:{backgroundColor:colors.danger,borderRadius:9,padding:10},rejectBtnText:{color:"#FFF",fontWeight:"800",textAlign:"center"},disabled:{opacity:.4},error:{color:colors.danger,textAlign:"right",fontSize:11}});
